mat <- matrix(1:9, nrow = 3, byrow = TRUE)
print(mat)
pt <- prop.table(mat)
sum_pt <- sum(pt)
print(pt)
print(sum_pt)
prop_table_row <- prop.table(mat, margin = 1)
prop_table_row_sum <- sum(prop_table_row)
print(prop_table_row)
print(prop_table_row_sum)
prop_table_col <- prop.table(mat, margin = 2)
prop_table_col_sum <- sum(prop_table_col)
print(prop_table_col)
print(prop_table_col_sum)
